name: build ios

on:
  workflow_call:
    inputs:
      vars_file:
        required: true
        type: string


jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: LOAD VARIABLES
        id: load-vars
        run: |
          # ------------> Loading variables...
          echo "SCHEME=$(yq e .variables.SCHEME ${{ inputs.vars_file }})" >> $GITHUB_OUTPUT
          echo "ORG=$(yq e .variables.ORG ${{ inputs.vars_file }})" >> $GITHUB_OUTPUT

          # echo "SCHEME=${SCHEME}" >> $GITHUB_OUTPUT
          # echo "ORG=${ORG}" >> $GITHUB_OUTPUT

      - name: SHOW VARIABLES
        run: |
          # ------------> showing variables...
          echo "SCHEME: ${{ steps.load-vars.outputs.SCHEME }}"
          echo "ORG: ${{ steps.load-vars.outputs.ORG }}"

      - name: RUN BUILD APPLICATION
        run: |
          # ------------> Building application...
          echo "SCHEME: ${{ steps.load-vars.outputs.SCHEME }}"
          echo "ORG: ${{ steps.load-vars.outputs.ORG }}"

      # - name: package
      #   run: |
      #     mkdir -p path/to/artifact
      #     echo hello > path/to/artifact/world.txt
      
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact-ios
      #     path: path/to/artifact/world.txt
