name: build ios

on:
  workflow_call:
    inputs:
      SCHEME:
        required: true
        type: string
      ORG:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: build ios project
        run: |
          echo "Buildando a aplicação iOS"
          echo ""
          echo "${{ inputs.SCHEME }}"
          echo "${{ inputs.ORG }}"


      # - name: package
      #   run: |
      #     mkdir -p path/to/artifact
      #     echo hello > path/to/artifact/world.txt
      
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact-ios
      #     path: path/to/artifact/world.txt
