name: obfuscate code ios

on:
  workflow_call:
    inputs:
      SCHEME:
        required: true
        type: string
      ORG:
        required: true
        type: string

jobs:
  obfuscate:
    runs-on: macos-latest
    steps:
      - name: obfuscate code
        run: |
          echo "--------------- OBFUSCATE CODE IOS!!--------------------"
          echo ""
          echo "${{ inputs.SCHEME }}"
          echo "${{ inputs.ORG }}"
