name: release ios app

on:
  workflow_call

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: release ios app
        run: |
          echo ""
          echo ""
          echo "Upload app to Registry"
          
