name: sonar scan ios
on:
  workflow_call:
    inputs:
      SCHEME:
        required: true
        type: string
      ORG:
        required: true
        type: string

jobs:
  scan-ios:
    runs-on: macos-latest
    steps:
      - name: run sonar scan
        run: |
          echo "----------------------------------------"
          echo " Run Sonar Scan"
          echo "${{ inputs.SCHEME }}"
          echo "${{ inputs.ORG }}"
          echo "----------------------------------------"
        
